<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>markdown</string>
		<string>yoc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
|&lt;!--(?!.*--&gt;)
|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
|^\s*--&gt;
|(^|\s)\}
)</string>
	<key>name</key>
	<string>YocDown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^&gt;+ .+$</string>
			<key>name</key>
			<string>markup.quote, punctuation.definition.blockquote.markdown</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>for inline raw</string>
			<key>match</key>
			<string>`[^`]+`</string>
			<key>name</key>
			<string>text.html.markdown markup.raw.inline</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.raw.block</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for markdown picture and url (complex)</string>
			<key>match</key>
			<string>!?\[(!?\[[^\]]*\]\([^\)]*\))\]\(([^\) ]*)\)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.raw.block</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for markdown picture and url (simple)</string>
			<key>match</key>
			<string>!?\[([^\]]*)\]\(([^\) ]*)\)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>for markdown unordered list</string>
			<key>match</key>
			<string>^([ ]{4}|\t)*([\*-] )</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>for markdown ordered list</string>
			<key>match</key>
			<string>^[0-9]+\.[ ]</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>for markdown separator</string>
			<key>match</key>
			<string>^([=-])\1{3,}$</string>
			<key>name</key>
			<string>meta.separator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>for markdown heading</string>
			<key>match</key>
			<string>^[#]+\s.+$</string>
			<key>name</key>
			<string>markdown.heading, markup.heading | markup.heading entity.name, markup.heading.markdown punctuation.definition.heading.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(cpp)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(c)\s*((?:linenos\s*)?%})?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(json)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(css)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(hbs|handlebars|html|html5)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.handlebars</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(javascript|js)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(java)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(md|markdown)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown.yocdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(python)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```|~~~|{%\s*highlight)\s*(shell|bash|sh)\s*((?:linenos\s*)?%})?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.fenced.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(```|~~~|{%\s*endhighlight\s*%})\n</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^---$</string>
			<key>comment</key>
			<string>for jekyll yaml front</string>
			<key>end</key>
			<string>^---$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#front-matter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for GFM: italic</string>
			<key>match</key>
			<string>([^a-zA-Z0-9-\.]|\s)(_[^\s_]+_)([^a-zA-Z0-9-\.]|\s)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for GFM: bold</string>
			<key>match</key>
			<string>(\*\*[^\s\*]+\*\*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for GFM: italic</string>
			<key>match</key>
			<string>([^a-zA-Z0-9-\.]|\s)(\*[^\s\*]+\*)([^a-zA-Z0-9-\.]|\s)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for GFM: bold</string>
			<key>match</key>
			<string>([^a-zA-Z0-9-\.]|\s)(__[^\s\*]+__)([^a-zA-Z0-9-\.]|\s)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.shell</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>for GFM: Strikethrough</string>
			<key>match</key>
			<string>(~~[^\s~]+~~)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(([ ]{4}|\t)+[^&lt;\*\s-].+\n)</string>
			<key>name</key>
			<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[\|+]([^\|+]+[\|+])+$</string>
			<key>comment</key>
			<string>for table</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.raw.block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.handlebars</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>front-matter</key>
		<dict>
			<key>comment</key>
			<string>for jekyll yaml front</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^([\s-]*[a-zA-Z0-9_-]+):([^#]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[^#]*(#.*)</string>
				</dict>
			</array>
		</dict>
		<key>link-footnote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>.?(\[)([^\]]*)(\])</string>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.yocdown</string>
	<key>uuid</key>
	<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
